// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // O CLI (migrate/db push) usa a conexão DIRETA (não passa pelo pooler).
    // O app em runtime usa DATABASE_URL (pooled) via adapter em src/lib/db.ts.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
